name: Build & Deploy to Truehost

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies based on package-lock.json
      - name: Install deps
        run: npm ci --include=optional

      # WORKAROUND: install Rollup’s Linux binary so Vite can find it
      - name: Install rollup-linux-x64-gnu
        run: npm install @rollup/rollup-linux-x64-gnu --no-save

      # Build the Vite app
      - name: Build
        run: npm run build

      # Deploy over FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/
          server-dir: public_html/
          log-level: standard
          exclude: |
            logs/**
            backups/**
            tmp/**
            cgi-bin/**
            api/**
            vendor/**
            composer.json
            composer.lock
