name: Build & Deploy to Truehost

on:
  push:
    branches: [ main ]   # ← change if you deploy from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'         # 'yarn' or 'pnpm' if you use those

      - name: Install deps
        run: npm ci            # or: npm i  (if package-lock.json is missing)

      # If using Vite + Vue Router history mode and the app is in a subfolder,
      # set base path before building, or configure vite.config.js accordingly.
      # - name: Set VITE_BASE for subfolder deploy
      #   run: echo "VITE_BASE=/your-subfolder/" >> $GITHUB_ENV

      - name: Build
        env:
          # Pass any runtime build envs here if you use them (Vite uses VITE_*).
          # VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      # Upload /dist to Truehost via FTPS (secure FTP)
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps             # or 'ftp' if FTPS isn’t enabled
          local-dir: dist/           # change if your build outputs elsewhere
          server-dir: public_html/   # change to your exact docroot/subfolder
          log-level: standard
