name: Build & Deploy to Truehost

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18 (npm 9)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Show npm version for sanity
      - name: Print npm version
        run: npm -v

      # Install using the lockfile + include optionals
      - name: Install deps
        run: npm ci --include=optional

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/
          server-dir: public_html/
          log-level: standard
          exclude: |
            logs/**
            backups/**
            tmp/**
            cgi-bin/**
            api/**
            vendor/**
            composer.json
            composer.lock
