name: Build & Deploy to Truehost

on:
  push:
    branches: [ main ]   # change if you deploy from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci    # use "npm i" if you don't have package-lock.json

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps                # explicit FTPS (port 21)
          local-dir: dist/              # Vite's default output
          server-dir: public_html/      # CHANGE if your Document Root is different
          log-level: standard
          # Optional: keep non-app folders on the server (won't delete these)
          exclude: |
            logs/**
            backups/**
            tmp/**
